### ISSUE TITLE
Feature request: Generation of DEPENDS.txt file

### ISSUE THREAD

**Issue by pablgonz** [latex3/l3build#121]
It would be nice if `l3build` could generate the [DEPENDS.txt](https://tug.org/texlive/pkgcontrib.html#deps).
Saludos

**Comment by FrankMittelbach** [comment]
Nice concept but how do you suggest that this is "generated"? It seems to me that in most cases the dependencies can not be automatically determined and need to be manually specified by the author of a package (if that would be possible that it could be done by CTAN). And providing the  `DEPENDS.txt` by the author is of course already now possible. So I'm not really sure  how this could be done.

**Comment by pablgonz** [comment]
@FrankMittelbach I was thinking of something _semi-automatic_, like the `MANIFEST.md` generation.

**Comment by FrankMittelbach** [comment]
@pablgonz well, MANIFEST is automatic in the sense that if you request it there is an algorithm to generate it, but for DEPENDS I don't see how that could be done (from build.lua or from something else reliably). If you have something concrete in mind, please sketch out that algorithm.  For example, if a package requires other packages you would only find out by scanning the .dtx file for `\RequirePackage` or some other loading requests but that is just a heuristic and there are possibly other dependencies that come about differently and none of that is anywhere stated in build.lua.

**Comment by blefloch** [comment]
For our repos we have isolated tests with the appropriate third-party packages
copied in a support/ directory.  Could we have a variable in build.lua (perhaps
we already have that under a different name)

testdependencies = amsmath.sty plain.tex

that would do two things: populate the DEPENDS.txt with a list of files, and
copy using essentially

for I in $testdependencies ; do
  cp `kpsewhich $I` build/test/ ;
done

before running isolated tests?

**Comment by pablgonz** [comment]
> @pablgonz  For example, if a package requires other packages you would only find out by scanning the .dtx file for `\RequirePackage` or some other loading requests but that is just a heuristic and there are possibly other dependencies that come about differently and none of that is anywhere stated in build.lua.
I think you have the power to read minds :) 
I was thinking about something like searching for `RequirePackage` first, but of course, there are circular dependencies that can't be obtained directly, but, maybe you could generate a small test that would generate `.fls` and read and sort them from there.

**Comment by pablgonz** [comment]
@blefloch That's a great idea. You could even have a little list on the `l3build` side of packages that are always present (I'm thinking latex-base) and that you don't need to add to the variable.

**Comment by davidcarlisle** [comment]
I'd be wary about this, it is already confusing enough that latex packages (as you'd find by scanning for requirepackage or looking in the support directory) are not the same thing as texlive package manager packages (as needed by the depends file). So I don't think l3build should merge the two things because it happens to work in some cases.

Also you would not be able to automate "conditional" dependencies, and an automatically produced bad depends file is worse than not supplying one at all. Given the amount of hand authoring it takes to produce a package; maintaining a depends list by hand and adding it to the l3build as a .txt file in the same way as readme etc, does not seem too much of a burden.

**Comment by josephwright** [comment]
I'm with @davidcarlisle here: dependencies are something one needs to document by hand. For a start, anything 'required' by LaTeX should *not* feature for a LaTeX package: kernel + required + tools + `babel` + `amsmath` (+ `l3kernel`) must be available.

**Comment by FrankMittelbach** [comment]
> For our repos we have isolated tests with the appropriate third-party packages copied in a support/ directory. Could we have a variable in build.lua (perhaps we already have that under a different name)

but the dependencies we test are in the opposite direction, those aren't works we require those are works that we might break

and it is not as if a `-recorder` of everything that gets loaded is a requirement on a package it just happened that it gets loaded in a test and may get loaded because some package in the test loads something else etc etc and may not do that tomorrow. So I'm with David and Joseph, I think it is really something that isn't reasonable to automate without false results and incorrect dependencies are worse than none. So my conclusion is still, it is best to be done manually by the package author.

What could heprhals be done is to point people in the l3build documentation to the fact that it can be sensible to include a DEPENDS.txt file and point them to that page but that is as far as I would go.

**Comment by pablgonz** [comment]
I think a mention of the `DEPENDS.txt.` file for TeX Live in the documentation for "large projects" might be useful, for the moment I think it is better to close this. Thanks
