### ISSUE TITLE
l3build ctan may fail when run on a single module in a bundle

### ISSUE THREAD

**Issue by kdv2005** [latex3/l3build#126]
When I run _l3build ctan_ in directory _examples/Bundle-Flat/Module-One_ in the master branch  it fails with error message _attempt to index a nil value_. 

I understand that this is not a conventional usage, but would you please consider enhancing l3build and these examples to make goal _ctan_ modular similar to _check_ and _doc_?

Here is the full transcript (TeXLive release 2020 on Windows)

```
MINGW64 ~/Documents/GitHub/l3build/examples/Bundle-Flat/Module-One (master)
$ l3build --version

l3build: A testing and building system for LaTeX

Release 2020-03-25
Copyright (C) 2014-2020 The LaTeX3 Project

MINGW64 ~/Documents/GitHub/l3build/examples/Bundle-Flat/Module-One (master)
$ l3build ctan
C:\texlive\2020\bin\win32\runscript.tlu:935: attempt to index a nil value

```

**Comment by josephwright** [comment]
The `ctan` target has to 'know' the structure which gets released. It's possible to set up a single shared set up with multiple parts that go to CTAN independently: that's why we have the idea of `bundles`, and if you look at the main `latex3` repo it's what we do to split `l3backend`, `l3kernel`, etc. But I don't see how one could reliably do what you've suggested: the naming for CTAN doesn't seem to make sense.

I can look to improve the error reporting here, but I think without a clear use case it's hard to make further suggestions.

**Comment by kdv2005** [comment]
Thank you, I withdraw this request.  When you have time please make ctan fail with more descriptive error in this case.

Upon further reflection I realized that I was trying to use 'ctan' as a one-step proxy for running end-to-end 'build, test, generate docs' for each module.   I agree that this is not the purpose of 'ctan'.
