### ISSUE TITLE
more rules in .gitignore

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#134]
Here are possible extensions:

1) ignore all hidden files.
2) ignore aux files created while running `pdflatex l3build.dtx`

```
.*
!/.gitignore

build/
*.pdf
*.zip
!testfiles/*.pdf

l3build.aux
l3build.glo
l3build.hd
l3build.idx
l3build.log
l3build.out
l3build.synctex.gz
l3build.toc
```

**Comment by zauguin** [comment]
About the second point: The reason that these aren't set is that normally the documentation is built using `l3build doc` which will automatically keep all the files under `build` which is already ignored. Maybe we should add more doumentation how to build the docs. Currently you have to read the document in order to figure out how to build it correctly I guess.

**Comment by FrankMittelbach** [comment]
@zauguin true, but I usually have those concerning local doc production in my projects as well, because often enough it is faster to run something locally while altering it and you don't want to checkin some .aux file etc by mistake because you do not clean up after yourself. So having those in .ignore make sense to me (regardless of some need to explain how the doc target works :-)

**Comment by zauguin** [comment]
Fair point. Maybe we should go for `*.aux` etc. though for future-proofing and to make the file more portable to other projects. (And to catch `texput.log` of which I have a shocking number floating around) I don't think that we ever want to check-in any such files.

**Comment by josephwright** [comment]
> About the second point: The reason that these aren't set is that normally the documentation is built using `l3build doc` which will automatically keep all the files under `build` which is already ignored. Maybe we should add more doumentation how to build the docs. Currently you have to read the document in order to figure out how to build it correctly I guess.

That plus I personally like being able to `git clean -f` when I accidentally run typesetting locally  ;)

**Comment by josephwright** [comment]
Should we standardise the team repos here? I can quickly edit all of the `.gitignore` files to add the typeset files

**Comment by FrankMittelbach** [comment]
> Should we standardise the team repos here? I can quickly edit all of the `.gitignore` files to add the typeset files

I would leave them alone. It is easy enough to mask something that shouldn't be masked and in the opposite direction updating that file individually when needed is no big deal.

**Comment by josephwright** [comment]
Looking back, I think we fixed this.
