### ISSUE TITLE
Documentation of checkformat variable

### ISSUE THREAD

**Issue by blefloch** [latex3/l3build#188]
In the documentation of `checkformat` I read
```
The format used for tests can be altered by setting \var{checkformat}:
the default setting \texttt{latex} means that tests are run using
\emph{e.g.}~\texttt{pdflatex}, whereas setting to \texttt{plain} will run
tests using \emph{e.g.}~\texttt{pdftex}.
(Currently, this should be one of \texttt{latex} or \texttt{plain}.)
```
But it seems that the correct value to test the plain format is not `plain` but rather `checkformat = tex`.  Since I am not certain, I'll let someone else fix the documentation or the code.  (This broke some package tests I had.)

**Comment by zauguin** [comment]
The documentation already mentioned further down

> the binary names is the same as the `engine`, and the format is a simple substitution
of the `checkformat` into `engine`, replacing `tex`.

which already implied using `tex` instead of `plain` for plain TeX which also gives a certain consistency, so I adjusted the documentation.

We could add `plain` as an alternative using `specialformats`, but that would need adjustment for every new engine (Which might seem uncommen but I tend to have some non standard engines around most of the time...) and I don't see a good reason for it anyway.
