### ISSUE TITLE
l3build fails for unknown reasons

### ISSUE THREAD

**Issue by niruvt** [latex3/l3build#328]
After an update, l3build is failing for unknown reasons. I get this in the terminal whenever I issue `l3build doc` in an `build.lua` equipped directory which used to compile earlier.

```
l3build doc
/usr/local/texlive/2023/bin/x86_64-linux/l3build: line 1: --[[: command not found
/usr/local/texlive/2023/bin/x86_64-linux/l3build: line 3: syntax error near unexpected token `('
/usr/local/texlive/2023/bin/x86_64-linux/l3build: line 3: `File l3build.lua Copyright (C) 2014-2022 The LaTeX Project'
```

**Comment by niruvt** [comment]
Sorry, after today's update the issue seems to have got resolved. Closing.

**Comment by muzimuzhi** [comment]
The problem that shebang (`#!/usr/bin/env texlua`) was missing in `l3build.lua` was introduced in https://github.com/latex3/l3build/commit/bbe66f5d8f9427a7d8014b5fad9e09c7bf201c01 (release [2023-12-12](https://github.com/latex3/l3build/releases/tag/2023-12-12)) and fixed in https://github.com/latex3/l3build/commit/8fd5875619dbc41abdbc748dc6e7529628aee7d3 (release [2023-12-13-2](https://github.com/latex3/l3build/releases/tag/2023-12-13-2)).

**Comment by niruvt** [comment]
@muzimuzhi 

Thanks for the references, sorry for the noise.
