### ISSUE TITLE
Rework setversion

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#40]
Based on @wspr's excellent Lua code in https://github.com/latex3/l3build/pull/34, I realise that the current `setversion` customisation is not ideal. It should deal with a file handle not a line of text (reflects a TeX background!). At the same time, I remain unhappy about using `-v` for 'version` here .. I think `-t` for `--tag` might be better ...

**Comment by FrankMittelbach** [comment]
yes |-v| is rather unfortunate as this is universially known as "tell me your version". I like |--tag| not sure you need the short form.

**Comment by josephwright** [comment]
Actually I probably should change how this works a bit: it would be better to require a tag name and go with
```
texlua build.lua tag [--date <date>] <name>
```
which is then pretty similar to _e.g._ Git's syntax.

**Comment by wspr** [comment]
I took a look at the code here and I actually don't mind the current approach.

With the manifest code it's important to pass around file handles because you're operating directly onto files as they're written. In the case of setversion the functionality seems more "contained" and simply dealing with a line of text encapsulates/simplifies what's going on.

It seems like using a file handle would add complexity for the user code — is there an advantage to doing this?

**Comment by josephwright** [comment]
@wspr The current code is limited to a line-by-line approach: one might expect that some users want to do more complex manipulation. 

As @FrankMittelbach  notes, using `-v` has always been awkward.

**Comment by wspr** [comment]
Oh, good point — it’s pretty understandable people might want to have something like

    \ProvidesExplPackage
        {…}
        {…}
        {…}
        {…}

and so on...
