### ISSUE TITLE
ln instead of cp for intermediate directory

### ISSUE THREAD

**Issue by maieul** [latex3/l3build#44]
Hi, 

to build the zip, l3build use a `cp` to `ctandir`. Why not using a ln ? It would be faster and save SSD lifetime

**Comment by wspr** [comment]
That does sound like an elegant approach. But can `ln` (and then the construction of the `zip` file) be done reliably on Windows as well?

I suppose even if not the difference could be abstracted away.

**Comment by josephwright** [comment]
I guess  the primary reason is as @wspr says that this may be tricky on Windows (`mklink` is not available to non-privileged users). I'm also not sure what happens if one makes a zip containing links, again particularly on Windows but also mindful of Linux/BSD differences.

If pushed, I think I'd also say that I prefer the idea of having a 'real' copy in each tree, such that separate parts of the build set up are truly 'safe' to be modified independent of others.

**Comment by FrankMittelbach** [comment]
@josephwright not sure this is an enhancement. Stick to the KISS principle here and do actions identical across platforms, i.e., copy.

**Comment by josephwright** [comment]
@FrankMittelbach  If you mean the labelling, it's not a bug and it's not a usage question, so it's a feature request ...

**Comment by FrankMittelbach** [comment]
well feature request \neq enhancement in my book but I guess that may be 
nit picking, so I'm happy enough to interpret that label this way from 
now on

**Comment by maieul** [comment]
personnaly, I used these technic on both linux and macos. But if it cause problem for windows, and also for @josephwright  I think we could close this issue

**Comment by FrankMittelbach** [comment]
that's the point really; back in the days when we used makefiles that only worked reasonably on unix or OSes that are close like OSX I would have agreed with you, but with something that really should behave identically as much as possible across all platforms we use copy is a better choice.

**Comment by wspr** [comment]
Seems like consensus is to close.
