### ISSUE TITLE
Support testing multiple Lua(TeX) versions

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#75]
As discussed with @u-fischer: testing for e.g. Lua 5.3.

**Comment by josephwright** [comment]
@u-fischer I didn't follow all of the Lua(TeX) version discussion carefully. In addition to picking up that `lua<whatever>` should be treated as `luatex`, what else do we need to work with multiple versions?

**Comment by davidcarlisle** [comment]
On Thu, 18 Oct 2018 at 07:41, Joseph Wright <notifications@github.com>
wrote:

> @u-fischer <https://github.com/u-fischer> I didn't follow all of the
> Lua(TeX) version discussion carefully. In addition to picking up that
> lua<whatever> should be treated as luatex, what else do we need to work
> with multiple versions?
>


Haven't tried the latest l3build yet but the other bit I had to change
before was the gsub logic to get the format name from the engine name

    format = " -fmt=" .. gsub(engine, "(.*)tex$", "%1") .. checkformat

assumes the engine name ends with tex so doesn't work for luatex53 unless
the format is called luatex53latex

**Comment by u-fischer** [comment]
Hm. I hope I remember everything. With the old version I managed to get l3build to test with luatex53 by using a format  "luatex53latex" and  `checkformat="latex" checkengines ={"luatex53"} 
stdengine={"luatex53"}`. I'm open about the name of the format, but imho you should assume that `-eluatex53`  and some format setting like `latex` can't call a wrapper like `lualatex` but must lead to something like `luatex53 --fmt=somesensiblename`. 

The following problem then was with normalization of the log. The checks failed due to differences in line length/breaks. That'as perhaps already covered by your changes. See https://chat.stackexchange.com/transcript/41?m=47107208#47107208

**Comment by josephwright** [comment]
@u-fischer  Latest checkin should allow `lualatex53` or similar as a name ...

**Comment by josephwright** [comment]
I'm going to hope this is now fixed: release coming today.
