### ISSUE TITLE
recordstatus=true code fails if checkruns is greater than 1 

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#90]
the code in l3build-check.lua loops over checkruns. If checkruns is greater than one but the test stops with success already after the first compilation, one gets an error as errlevel[2] is not defined.

~~~~
  if recordstatus then
    new_content = new_content .. '***************' .. os_newline
    for i = 1, checkruns do
      new_content = new_content ..
        'Compilation ' .. i .. ' of test file completed with exit status ' ..
        errlevels[i] .. os_newline
    end
  end
~~~~

~~~~
C:\texlive\2018\bin\win32\runscript.tlu:922: ...exlive/2018/texmf-dist/scripts/l3build/l3build-check.lua:284: attempt to concatenate field '?' (a nil value)
~~~~

**Comment by frougon** [comment]
Hello,

I see this on Linux too (TL 2019 from Debian unstable). I'll add notes which may be tangential to the actual problem but seem important to me, as they affect, unless I'm mistaken, the correctness of the exit statuses we are trying to compare when using `recordstatus = true`.

As anyone reading the code can see, `errlevels` is filled using `run()` which is a wrapper for Lua's `os.execute()`, and this is where I found something strange. With `texlua`, it seems to me that `os.execute()` is affected by an [old Lua bug](http://lua.2524044.n2.nabble.com/os-execute-returns-mangled-exit-code-on-linux-td7645762.html). According to the [Lua Reference Manual](http://www.lua.org/manual/5.3/manual.html#6.9),  `os.execute()` should return three values, and this is indeed what happens if I use `/usr/bin/lua5.3` from the `lua5.3` package in Debian:

```
$ /usr/bin/lua5.3 =(echo 'print( os.execute("exit 1") )')
nil     exit    1
```

(this is Zsh syntax to run a temporary Lua script file containing `print( os.execute("exit 1") )`). However, with `texlua`, the output of the same script is... strange:

```
$ texlua =(echo 'print( os.execute("exit 1") )')
256
```

This despite `texlua` reporting the same version:

```
$ texlua =(echo 'print(_VERSION)')
Lua 5.3
```
